import {
  SiGraphql,
  SiMaterialui,
  SiMongodb,
  SiNextdotjs,
  SiNodedotjs,
  SiPostgresql,
  SiRedis,
  SiSass,
  SiTypescript,
} from "react-icons/si";
import { IoLogoCss3 } from "react-icons/io";
import { DiJavascript1 } from "react-icons/di";
import { FaReact } from "react-icons/fa";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={styles.nav}>
        <div className={styles.navContainer}>
          <span className={styles.logo}> Shuo Tian</span>
          <ul className={styles.navLink}>
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <Link href="/blogs">Blogs</Link>
            </li>
          </ul>
        </div>
      </nav>

      <div className={styles.container}>
        <main className={styles.main}>
          <h1>
            Hello, my name is{" "}
            <span className={styles.name}>
              {"Shuo Tian".split("").map((char, i) => (
                <span key={i}>{char}</span>
              ))}
            </span>
            , a front-end developer.
          </h1>
          <div className={styles.photo}>
            <Image src="/photo.jpg" width={300} height={300} alt="my photo" />
            <div className={styles.photoTag}>hot</div>
          </div>
          <div className={styles.details}>
            <h2>I know these skills...</h2>
            <ul className={styles.skills}>
              <li>
                <SiTypescript color="#007acc" /> TypeScript &lt;3
              </li>
              <li>
                <DiJavascript1 color="#F0DB4F" />
                JavaScript
              </li>
              <li>
                <FaReact color="#61DBFB" /> React.js
              </li>
              <li>
                <SiNextdotjs color="white" /> Next.js
              </li>
              <li>
                <IoLogoCss3 color="#264de4" /> CSS / <SiSass color="#CD6799" />
                SASS
              </li>
              <li>
                <SiMaterialui color="#007FFF" /> MaterialUI
              </li>
              <li>
                <SiGraphql color="#e535ab" /> GraphQL
              </li>
              <li>
                <SiPostgresql color="326690" /> SQL
              </li>
              <li>
                NoSQL (<SiMongodb color="4DB33D" /> MongoDB,{" "}
                <SiRedis color="D82C20" />
                Redis...)
              </li>
              <li>
                <Image src="/python.png" alt="python" height={16} width={16} />{" "}
                Python!!!
              </li>
              <li>
                <SiNodedotjs color="#3C873A" />
                Node.js
              </li>
            </ul>
          </div>
        </main>
      </div>
      <footer className={styles.footer}></footer>
    </>
  );
};

export default Home;
